// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO profiles (user_id, display_name)
VALUES ($1, $2)
ON CONFLICT (user_id) DO NOTHING
`

type UpsertProfileParams struct {
	UserID      uuid.UUID
	DisplayName string
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.Exec(ctx, upsertProfile, arg.UserID, arg.DisplayName)
	return err
}
