// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countProfiles = `-- name: CountProfiles :one
SELECT count(*)
FROM profiles
WHERE ($1::text = '' OR display_name ILIKE '%' || $1 || '%')
`

func (q *Queries) CountProfiles(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countProfiles, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (user_id, display_name)
VALUES ($1, $2)
RETURNING user_id, display_name, bio, avatar_url, phone, created_at, updated_at
`

type CreateProfileParams struct {
	UserID      uuid.UUID
	DisplayName string
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.UserID, arg.DisplayName)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles WHERE user_id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfile, userID)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT user_id, display_name, bio, avatar_url, phone, created_at, updated_at
FROM profiles
WHERE user_id = $1
`

func (q *Queries) GetProfile(ctx context.Context, userID uuid.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile, userID)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT user_id, display_name, bio, avatar_url, phone, created_at, updated_at
FROM profiles
WHERE ($1::text = '' OR display_name ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProfilesParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListProfiles(ctx context.Context, arg ListProfilesParams) ([]Profile, error) {
	rows, err := q.db.Query(ctx, listProfiles, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarUrl,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET display_name = COALESCE($1, display_name),
    bio          = COALESCE($2, bio),
    avatar_url   = COALESCE($3, avatar_url),
    phone        = COALESCE($4, phone),
    updated_at   = now()
WHERE user_id = $5
RETURNING user_id, display_name, bio, avatar_url, phone, created_at, updated_at
`

type UpdateProfileParams struct {
	DisplayName *string
	Bio         *string
	AvatarUrl   *string
	Phone       *string
	UserID      uuid.UUID
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
		arg.Phone,
		arg.UserID,
	)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
